
version: 2.1
orbs:
  android: circleci/android@2.1.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:

    docker:
      # specify the version you desire here
      - image: cimg/android:2023.02
      # - image: circleci/android:api-28
      # - image: circleci/openjdk:latest


    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx4096m
    # Add steps to the job

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "firstAndroidLibrary/build.gradle" }}

      - run: 
          name: change the permission
          command: chmod +x ./gradlew

      - run: 
          name: download gradle dependencies
          command: ./gradlew androidDependencies 

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "firstAndroidLibrary/build.gradle" }}

      # build the androidlib
      - run: 
          name: build project
          command: ./gradlew clean build

      # run tests!
      - run: 
          name: gradle unit tests
          command: ./gradlew lint test
 
  android-test:
    executor:
      name: android/android-machine
      tag: "202102-01"
      resource-class: large

    #run instrumentation tests

    steps:
      - checkout
      - run:
          name: installing emulator and Running Instrumentation tests
          command:  |
            sdkmanager "platform-tools" "platforms;android-29" "build-tools;30.0.0" "emulator"
            sdkmanager "system-images;android-29;google_apis;x86"
            echo no | avdmanager create avd -n test-emulator -k "system-images;android-29;google_apis;x86"
            emulator -avd test-emulator -noaudio -no-boot-anim -gpu off -no-window &
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
            adb shell wm dismiss-keyguard
            sleep 1
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            ./gradlew connectedAndroidTest
       

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - run:
          name: Build and deploy package
          command: |
            ./gradlew assemblyRelease publish


workflows:
  build-androidTest-deploy:
    jobs:
      - build
      - android-test:
          requires:
            - build
      - deploy:
          requires:
            - android-test

